branch-defaults:
  master:
    environment: null
    group_suffix: null
global:
  application_name: pharmacy
  branch: master
  default_ec2_keyname: vockey
  default_platform: Python 3.9 running on 64bit Amazon Linux 2023
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: origin
  sc: git
  workspace_type: Application
